/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.utexas.cs345.jdblisp.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int NIL = 9;
  /** RegularExpression Id. */
  int NUMB = 10;
  /** RegularExpression Id. */
  int STRG = 11;
  /** RegularExpression Id. */
  int SYMB = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\n\\r\"",
    "\";.*$\"",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "<NUMB>",
    "<STRG>",
    "<SYMB>",
  };

}
